services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - firefox/config:/config
      - type: bind
        source: /PVE-NAS/Downloads
        destination: firefox/Downloads
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
volumes:
  firefox:
